### ISSUE TITLE
Why do we need to distinguish between L3 and L2 neighbors?

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#363]
Question from Slack alcor channel: Why do we need to distinguish between L3 and L2 neighbors?

Imagine Port1 (from green subnet) on Host1, Port2 (also from green subnet) on Host2, during Port1 creation, we need to program Port2 as Port1's L2 neighbor, so that we can create the ovs outport and openflow rule for Port1 to talk to Port2 *directly*.

Now imagine Port1 (from green subnet) on Host1, Port2 (from red subnet) on Host2. Without router connected between green and red subnet, Port1 and Port2 cannot talk to each other. Say we created a router to connect green subnet and red subnet together, during Port1 creation, we need to program Port2 as Port1's L3 neighbor, that's to add Alcor Distributed Router rule so that we can route packet coming from Port1 to the red subnet on Host1, and then send it to Port2 on Host2. L2 neighbor programming mentioned in the previous paragraph will also be done to allow cross host communication.

Reference on the on host routing design: https://github.com/futurewei-cloud/alcor/blob/master/docs/modules/ROOT/pages/high_level/routing_design.adoc

**Comment by chenpiaoping** [comment]
"that's to add Alcor Distributed Router rule so that we can route packet coming from Port1 to the red subnet on Host1" --->Add the route to the red subnet on router and add the arp entry for Port2(or learn the mac address of port2 through the arp protocol?) When data packet arrive at the br-int bridge from the interface of router, Br-int and br-tun treat it the same way as L2 (br-int adds vlan_id to it and br-tun encapsulates vxlan headers according to vlan_id). So we just need to add L2 neighbor information on the br-tun bridge?
